dist: xenial
group: edge
language: python
os: linux
services:
  - docker

jobs:
  include:
    - env: DIST=centos-8
    - env: DIST=centos-9
    - env: DIST=fedora-34
    - env: DIST=fedora-35

before_install:
  - docker pull quay.io/ovirt/imageio-test-$DIST
  - sudo ci/configure-docker.py

script:
  - |
    docker run \
    --privileged \
    --rm \
    -it \
    --volume `pwd`:/src:Z \
    quay.io/ovirt/imageio-test-$DIST \
    bash -c "cd /src && ci/test.sh"
