archs:
  - x86_64:
      distributions:
        - el8
  - ppc64le:
      distributions:
        - el8

stages:
  - check-patch:
      archs:
        - x86_64
  - build-artifacts:
      substages:
      - py3

release-branches:
  master:
  - ovirt-master
  ovirt-4.3:
  - ovirt-4.3
  ovirt-4.2:
  - ovirt-4.2
